services:
  backend:
    container_name: te_backend
    build:
      context: .
    env_file:
      - .env
    ports:
      - "9000:3000"
    restart: unless-stopped
  #
  # db:
  #   image: postgres:16-alpine
  #   container_name: te_db
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "${POSTGRES_PORT:-54321}:5432"
  #   restart: unless-stopped
